# -*- coding: utf-8 -*-
"""preprocessing and visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sAId9WKxZAHi9MMmWLB7kY_ZKVqGQNPw

**Data Science  Assignment**
---


STD Name:Mohammed Yehia Ashour

---


STD ID:1301195595

---

[Github](https://github.com/Moudyash/preprocessing_and_visualization)
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
from collections import Counter
from pandas.plotting import scatter_matrix

"""   # *** Preprocessing  Section***:"""

data=pd.read_csv('C:\Users\Medo\Desktop\preprocessing_and_visualization\University_data.csv',na_values=['?','UNDEFIND'])
data

data.info()

print("Check if Data Contain A null Value")

print(data.isnull().sum())
data.isnull()

mask=data.isnull().any(axis=0)
mask.head(10)

total_num_null=mask.sum()/len(data)
total_num_null

data=data.fillna({'GRE Score':data['GRE Score'].mean()})
data=data.fillna({'TOEFL Score':data['TOEFL Score'].mean()})
#counter = Counter(data["University Rating"])
#print(counter.most_common(3)[0][0])
#data["University Rating"].fillna( method ='ffill', inplace = True)
#data=data.fillna({'University Rating':data['University Rating'].mean()})
data=data.fillna({'SOP':data['SOP'].mean()})
data=data.fillna({'LOR ':data['LOR '].mean()})
data=data.fillna({'CGPA':data['CGPA'].mean()})

data

mask=data.isnull().any(axis=0)

mask.head(10)

counter = Counter(data["Research"])
print(counter.most_common(3)[0][0])
data["Research"].fillna( method ='ffill', inplace = True)
counter2 = Counter(data["University Rating"])
data["Research"].fillna( method ='ffill', inplace = True)

mask=data.isnull().any(axis=0)
print("Check if Data Contain A null Value")

print(data.isnull().sum())
mask.head(10)

"""# *** Visualization Section***:

*Heatmap*
"""

sns.scatterplot(x='GRE Score', y='TOEFL Score', data=data,hue="University Rating",color='purple', size=10)
plt.show()

plt.figure(figsize=(20,6))

sns.lineplot(data=data[["TOEFL Score","GRE Score","University Rating"]])

data.hist(figsize=(10,10))
plt.show()

plt.figure(figsize=(10,6))

# Add title
plt.title('Average Chance of Admit by University Rating', fontsize=18, color='blue')

# Bar chart showing average arrival delay for Spirit Airlines flights by month
sns.barplot(data=data, x='University Rating', y='Chance of Admit', hue='Research')
# Add label for vertical axis
plt.ylabel("Chance of Admit")

sns.barplot(data=data, x='University Rating', y='Chance of Admit')

plt.figure(figsize=(10,6))

#sns.lmplot(data=data, x='CGPA', y='Chance of Admit',hue="Research"
# Create the plot
ax = sns.lmplot(data=data, x='CGPA', y='Chance of Admit', hue='Research', scatter_kws={'alpha': 0.5}, line_kws={'linewidth': 2})

# Add a title
plt.suptitle('Relationship between CGPA and Chance of Admit')
# Label the axes

plt.xlabel('CGPA')
plt.ylabel('Chance of Admit')

# Add a legend
plt.legend(title='Research')

# Add statistical annotations
sns.regplot(data=data, x='CGPA', y='Chance of Admit', ci=95, scatter=False)

"""The resulting plot will show a scatter plot with a fitted regression line for each 'Research' category, with the 'CGPA' values on the x-axis and the 'Chance of Admit' values on the y-axis. The regression lines will show the trend of the data and can be used to predict the 'Chance of Admit' based on the 'CGPA' values. The plot will also show the distribution of the data points for each 'Research' category, with different colors or marker styles used to differentiate the categories"""

sns.kdeplot(data=data, x='Chance of Admit', hue='Research', shade=True)

"""

This visualization shows that the distribution of 'Chance of Admit' is slightly higher for students who have completed research compared to students who have not completed research. This suggests that students who have completed research may have a slightly higher chance of admission to the university. However, it is important to note that this is a continuous variable, and the confidence intervals for each category overlap significantly, so the difference in the mean values may not be statistically significant.

Additionally, the visualization plot shows that the majority of students have a chance of admission between 0.6 and 0.8, with fewer students having a chance above 0.8 or below 0.6. This suggests that most students have a relatively similar chance of admission, with a few students having a higher or lower chance.
"""

sns.scatterplot(x=data['CGPA'], y=data['Chance of Admit'], hue=data['Research'])

"""Chance of Admit'. It shows that as the CGPA increases, the chance of admission also tends to increase."""

plt.figure(figsize=(10,6))

sns.histplot(data=data, x='CGPA', hue='Research')

# Set the width and height of the figure
plt.figure(figsize=(14,6))

# Add title
plt.title('Relationship between GRE Score and Chance of Admit')
sns.lineplot(data=data, x='GRE Score', y='Chance of Admit', hue='Research')
# Add label for horizontal axis
plt.xlabel("GRE Score")
plt.ylabel("Chance of Admit")

scatter_matrix(data[['GRE Score', 'TOEFL Score', 'CGPA']], alpha=0.2, figsize=(6, 6), diagonal='hist', marker='o')



sns.boxplot(data=data, y='Chance of Admit', color='green', width=0.5)

"""The box in the plot represents the interquartile range (IQR) of the 'Chance of Admit' values, which is the range between the first quartile (25th percentile) and the third quartile (75th percentile). The line inside the box represents the median value (50th percentile). The whiskers extend from the box to show the minimum and maximum values, which are the lowest and highest values within 1.5 times the IQR of the median. Any points outside the whiskers are considered outliers and are plotted separately as individual points.

By interpreting the boxplot, you can get a sense of the spread and skewness of the 'Chance of Admit' values in the dataset, as well as identify any potential outliers. For example, if the box is narrow and the whiskers are short, it indicates that the values are concentrated around the median and there are few outliers. If the box is wide and the whiskers are long, it indicates that the values
"""